global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      server: 'global-monitor'
scrape_configs:
  - job_name: 'federate'
    scrape_interval: 15s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job="node-exporter-master1"}'
        - '{job="node-exporter-master2"}'
        - '{job="node-exporter-work1"}'
        - '{job="node-exporter-work2"}'
        - '{job="node-exporter-work3"}'
        - '{job="node-exporter-work4"}'
        - '{job="gateway"}'
        - '{job="docker-daemon"}'
    static_configs:
      - targets:
        - '172.17.0.1:31121'
        - '172.17.0.1:31119'
  - job_name: 'data-log-host'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.22.14.13:9100','10.22.15.13:9100']
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - cadvisor:8080

